@echo off
title Iniciando a API.
echo .............................................................
echo ................. Gerador de planilhas de viagens ...........
echo .............................................................
echo
env\Scripts\activate && python Main/massops.py 