@echo off
title Iniciando a API.
echo .............................................................
echo ................. A Tela vai iniciar ........................
echo .............................................................
echo
env\Scripts\activate && python Main/massops.py 