"IDAtracacao",
"TEsperaAtracacao",
"TEsperaInicioOp",
"TOperacao",
"TEsperaDesatracacao",
"TAtracado",
"TEstadia",
"CDTUP",
"IDBerco",
"Berço",
"Porto Atracação",
"Apelido Instalação Portuária",
"Complexo Portuário",
"Tipo da Autoridade Portuária",
"Data Atracação",
"Data Chegada",
"Data Desatracação",
"Data Início Operação",
"Data Término Operação",
"Ano",
"Mes",
"Tipo de Operação",
"Tipo de Navegação da Atracação",
"Nacionalidade do Armador",
"FlagMCOperacaoAtracacao",
"Terminal",
"Município",
"UF",
"SGUF",
"Região Geográfica",
"Nº da Capitania" ,
"Nº do IMO",